// Materialize a local payment + asaas_charges row for payments
// auto-generated by an Asaas subscription.
//
// When Asaas billing cycle triggers, it creates a new payment under
// the subscription. The webhook delivers PAYMENT_CREATED, but no
// local payment or asaas_charges row exists yet. This module fills
// that gap so the normal charge-sync pipeline can proceed.
//
// Called from processWebhookEvent when:
//   1. loadChargeByAsaasPaymentId returns null (no existing charge)
//   2. payload.payment.subscription is non-null
//
// Uses admin client (service_role) because webhooks have no user session.

import type { SupabaseClient } from '@supabase/supabase-js';
import type { LocalChargeRow } from './charge-sync';
import type { AsaasWebhookPaymentData } from './webhook-types';

type AdminSupabaseClient = SupabaseClient;

// ─── Types ───────────────────────────────────────────────────────

export interface MaterializeResult {
  charge: LocalChargeRow;
  localPaymentId: string;
  action: 'materialized';
}

interface AsaasSubscriptionLink {
  id: string;
  subscription_id: string;
  academy_id: string;
  asaas_account_id: string;
  asaas_customer_id: string;
  environment: string;
}

interface LocalSubscriptionCore {
  id: string;
  student_id: string;
}

// ─── Billing type → local method mapping ─────────────────────────

const BILLING_TYPE_TO_METHOD: Record<string, string> = {
  PIX: 'pix',
  BOLETO: 'boleto',
  CREDIT_CARD: 'card',
  UNDEFINED: 'manual',
};

function toLocalMethod(billingType: string): string {
  return BILLING_TYPE_TO_METHOD[billingType] ?? 'manual';
}

// ─── Due date formatting ─────────────────────────────────────────

function toTimestamptz(dateStr: string): string {
  // Asaas sends dates as YYYY-MM-DD. Convert to ISO timestamp for
  // the payments.due_date column (timestamptz).
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    return `${dateStr}T00:00:00.000Z`;
  }
  return dateStr;
}

function toDateOnly(dateStr: string): string {
  if (/^\d{4}-\d{2}-\d{2}$/.test(dateStr)) {
    return dateStr;
  }
  const d = new Date(dateStr);
  if (isNaN(d.getTime())) {
    return dateStr;
  }
  return d.toISOString().split('T')[0];
}

// ─── Lookup subscription link ────────────────────────────────────

async function findSubscriptionLink(
  supabase: AdminSupabaseClient,
  asaasSubscriptionId: string,
): Promise<AsaasSubscriptionLink | null> {
  const { data, error } = await supabase
    .from('asaas_subscriptions')
    .select('id, subscription_id, academy_id, asaas_account_id, asaas_customer_id, environment')
    .eq('asaas_subscription_id', asaasSubscriptionId)
    .maybeSingle();

  if (error) {
    throw new Error(`Erro ao buscar asaas_subscriptions para ${asaasSubscriptionId}: ${error.message}`);
  }

  return data as AsaasSubscriptionLink | null;
}

// ─── Lookup local subscription (for student_id) ──────────────────

async function loadLocalSubscriptionCore(
  supabase: AdminSupabaseClient,
  subscriptionId: string,
): Promise<LocalSubscriptionCore> {
  const { data, error } = await supabase
    .from('subscriptions')
    .select('id, student_id')
    .eq('id', subscriptionId)
    .single();

  if (error || !data) {
    throw new Error(`Subscription local ${subscriptionId} não encontrada: ${error?.message ?? 'not found'}`);
  }

  return data as LocalSubscriptionCore;
}

// ─── Create local payment ────────────────────────────────────────

async function createLocalPayment(
  supabase: AdminSupabaseClient,
  input: {
    academyId: string;
    subscriptionId: string;
    studentId: string;
    amount: number;
    method: string;
    dueDate: string;
  },
): Promise<string> {
  const { data, error } = await supabase
    .from('payments')
    .insert({
      academy_id: input.academyId,
      subscription_id: input.subscriptionId,
      student_id: input.studentId,
      amount: input.amount,
      currency: 'BRL',
      status: 'pending',
      method: input.method,
      due_date: toTimestamptz(input.dueDate),
    })
    .select('id')
    .single();

  if (error || !data) {
    throw new Error(`Erro ao criar payment local para subscription: ${error?.message ?? 'unknown'}`);
  }

  return (data as { id: string }).id;
}

// ─── Create asaas_charges row ────────────────────────────────────

async function createChargeLink(
  supabase: AdminSupabaseClient,
  input: {
    academyId: string;
    paymentId: string;
    asaasAccountId: string;
    asaasCustomerId: string;
    environment: string;
    asaasPaymentId: string;
    asaasSubscriptionId: string;
    externalReference: string | null;
    billingType: string;
    asaasStatus: string;
    value: number;
    netValue: number | null;
    dueDate: string;
    paymentDate: string | null;
    invoiceUrl: string | null;
    bankSlipUrl: string | null;
  },
): Promise<LocalChargeRow> {
  const { data, error } = await supabase
    .from('asaas_charges')
    .insert({
      academy_id: input.academyId,
      payment_id: input.paymentId,
      asaas_account_id: input.asaasAccountId,
      asaas_customer_id: input.asaasCustomerId,
      environment: input.environment,
      asaas_payment_id: input.asaasPaymentId,
      asaas_subscription_id: input.asaasSubscriptionId,
      external_reference: input.externalReference,
      billing_type: input.billingType,
      asaas_status: input.asaasStatus,
      value: input.value,
      net_value: input.netValue,
      due_date: toDateOnly(input.dueDate),
      payment_date: input.paymentDate ? toDateOnly(input.paymentDate) : null,
      invoice_url: input.invoiceUrl,
      bank_slip_url: input.bankSlipUrl,
      synced_at: new Date().toISOString(),
    })
    .select('id, academy_id, payment_id, asaas_account_id, environment, asaas_payment_id, external_reference, billing_type, asaas_status, value, net_value, due_date, payment_date, invoice_url, bank_slip_url, synced_at')
    .single();

  if (error || !data) {
    throw new Error(`Erro ao criar asaas_charges para payment de subscription: ${error?.message ?? 'unknown'}`);
  }

  return data as LocalChargeRow;
}

// ─── Main: materialize ───────────────────────────────────────────

/**
 * Given a webhook payment payload that belongs to an Asaas subscription,
 * create the corresponding local payment + asaas_charges row.
 *
 * Returns null if no matching asaas_subscriptions link is found
 * (the subscription was not created through MoveAccess).
 *
 * @throws on database errors (payment creation, charge creation)
 */
export async function materializeSubscriptionPayment(
  supabase: AdminSupabaseClient,
  paymentData: AsaasWebhookPaymentData,
): Promise<MaterializeResult | null> {
  const asaasSubscriptionId = paymentData.subscription;

  if (!asaasSubscriptionId) {
    return null;
  }

  // 1. Find the subscription link
  const subLink = await findSubscriptionLink(supabase, asaasSubscriptionId);

  if (!subLink) {
    // Subscription not managed by MoveAccess — can't materialize
    return null;
  }

  // 2. Load local subscription to get student_id
  const localSub = await loadLocalSubscriptionCore(supabase, subLink.subscription_id);

  // 3. Map billing type to local method
  const localMethod = toLocalMethod(paymentData.billingType);

  // 4. Create local payment
  const localPaymentId = await createLocalPayment(supabase, {
    academyId: subLink.academy_id,
    subscriptionId: subLink.subscription_id,
    studentId: localSub.student_id,
    amount: paymentData.value,
    method: localMethod,
    dueDate: paymentData.dueDate,
  });

  // 5. Create asaas_charges row linking to the new local payment
  const charge = await createChargeLink(supabase, {
    academyId: subLink.academy_id,
    paymentId: localPaymentId,
    asaasAccountId: subLink.asaas_account_id,
    asaasCustomerId: subLink.asaas_customer_id,
    environment: subLink.environment,
    asaasPaymentId: paymentData.id,
    asaasSubscriptionId,
    externalReference: paymentData.externalReference,
    billingType: paymentData.billingType,
    asaasStatus: paymentData.status,
    value: paymentData.value,
    netValue: paymentData.netValue,
    dueDate: paymentData.dueDate,
    paymentDate: paymentData.paymentDate,
    invoiceUrl: paymentData.invoiceUrl,
    bankSlipUrl: paymentData.bankSlipUrl,
  });

  return {
    charge,
    localPaymentId,
    action: 'materialized',
  };
}
