-- ASAAS CHARGES — Add subscription link column
-- PR #7: Correlate payments auto-generated by Asaas subscriptions
--
-- When Asaas creates a payment from a recurring subscription, we need
-- to know which subscription generated it. This column stores the
-- asaas_subscription_id (e.g. "sub_xxx") from the payment payload.
--
-- Nullable because standalone charges (created via create-charge) have
-- no subscription origin.

ALTER TABLE public.asaas_charges
  ADD COLUMN IF NOT EXISTS asaas_subscription_id text NULL;

-- Index for lookups: "all charges generated by this subscription"
CREATE INDEX IF NOT EXISTS idx_asaas_charges_asaas_subscription_id
  ON public.asaas_charges (asaas_subscription_id)
  WHERE asaas_subscription_id IS NOT NULL;

COMMENT ON COLUMN public.asaas_charges.asaas_subscription_id
  IS 'ID da subscription no Asaas que gerou este payment (ex: sub_xxx). NULL para cobranças avulsas.';
