-- ASAAS SUBSCRIPTIONS — External subscription link
-- PR #6: Recurring subscription integration with Asaas
--
-- This table links a local MoveAccess subscription to an external
-- Asaas subscription object. One local subscription maps to at most
-- one external Asaas subscription at this stage.
--
-- The table stores enough metadata to:
--   - Correlate future webhook events / payments generated by the sub
--   - Support future reconciliation (sync status, value, cycle, next_due_date)
--   - Track which Asaas account and customer were used
--   - Differentiate sandbox vs production

CREATE TABLE IF NOT EXISTS public.asaas_subscriptions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Local domain references
  subscription_id uuid NOT NULL REFERENCES public.subscriptions(id) ON DELETE RESTRICT,
  academy_id uuid NOT NULL REFERENCES public.academies(id) ON DELETE CASCADE,

  -- Asaas context
  asaas_account_id uuid NOT NULL REFERENCES public.asaas_accounts(id) ON DELETE RESTRICT,
  asaas_customer_id uuid NOT NULL REFERENCES public.asaas_customers(id) ON DELETE RESTRICT,
  environment text NOT NULL,

  -- External identifiers
  asaas_subscription_id text NOT NULL,
  external_reference text NOT NULL DEFAULT '',

  -- External state snapshot (kept in sync by webhooks / reconciliation)
  asaas_status text NOT NULL DEFAULT 'ACTIVE',
  billing_type text NOT NULL,
  cycle text NOT NULL,
  value numeric(12,2) NOT NULL,
  next_due_date date NULL,
  end_date date NULL,
  max_payments integer NULL,
  description text NOT NULL DEFAULT '',

  -- Sync tracking
  synced_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  -- Constraints
  CONSTRAINT asaas_subscriptions_environment_check
    CHECK (environment IN ('sandbox', 'production')),

  CONSTRAINT asaas_subscriptions_asaas_status_check
    CHECK (asaas_status IN ('ACTIVE', 'EXPIRED', 'INACTIVE')),

  CONSTRAINT asaas_subscriptions_billing_type_check
    CHECK (billing_type IN ('UNDEFINED', 'BOLETO', 'CREDIT_CARD', 'PIX')),

  CONSTRAINT asaas_subscriptions_cycle_check
    CHECK (cycle IN ('WEEKLY', 'BIWEEKLY', 'MONTHLY', 'BIMONTHLY', 'QUARTERLY', 'SEMIANNUALLY', 'YEARLY')),

  CONSTRAINT asaas_subscriptions_value_check
    CHECK (value > 0)
);

-- One external subscription per local subscription (enforces no-duplication)
CREATE UNIQUE INDEX IF NOT EXISTS idx_asaas_subscriptions_subscription_id
  ON public.asaas_subscriptions (subscription_id);

-- External ID must be globally unique within the table
CREATE UNIQUE INDEX IF NOT EXISTS idx_asaas_subscriptions_asaas_sub_id
  ON public.asaas_subscriptions (asaas_subscription_id);

-- Lookup by academy
CREATE INDEX IF NOT EXISTS idx_asaas_subscriptions_academy_id
  ON public.asaas_subscriptions (academy_id);

-- Lookup by Asaas account (useful for reconciliation)
CREATE INDEX IF NOT EXISTS idx_asaas_subscriptions_asaas_account_id
  ON public.asaas_subscriptions (asaas_account_id);

-- Lookup by status (useful for batch operations)
CREATE INDEX IF NOT EXISTS idx_asaas_subscriptions_asaas_status
  ON public.asaas_subscriptions (asaas_status);

-- Auto-update updated_at on changes
DROP TRIGGER IF EXISTS asaas_subscriptions_updated_at ON public.asaas_subscriptions;
CREATE TRIGGER asaas_subscriptions_updated_at
  BEFORE UPDATE ON public.asaas_subscriptions
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ─── RLS ─────────────────────────────────────────────────────────
-- Same pattern as asaas_charges: staff members of the academy can view/insert/update.

ALTER TABLE public.asaas_subscriptions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Staff view asaas_subscriptions in academy" ON public.asaas_subscriptions;
CREATE POLICY "Staff view asaas_subscriptions in academy"
ON public.asaas_subscriptions
FOR SELECT
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.academy_memberships am ON am.profile_id = p.id
    WHERE p.id = auth.uid()
      AND p.user_type = 'staff'
      AND am.academy_id = asaas_subscriptions.academy_id
  )
);

DROP POLICY IF EXISTS "Staff insert asaas_subscriptions in academy" ON public.asaas_subscriptions;
CREATE POLICY "Staff insert asaas_subscriptions in academy"
ON public.asaas_subscriptions
FOR INSERT
TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.academy_memberships am ON am.profile_id = p.id
    WHERE p.id = auth.uid()
      AND p.user_type = 'staff'
      AND am.academy_id = asaas_subscriptions.academy_id
  )
);

DROP POLICY IF EXISTS "Staff update asaas_subscriptions in academy" ON public.asaas_subscriptions;
CREATE POLICY "Staff update asaas_subscriptions in academy"
ON public.asaas_subscriptions
FOR UPDATE
TO authenticated
USING (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.academy_memberships am ON am.profile_id = p.id
    WHERE p.id = auth.uid()
      AND p.user_type = 'staff'
      AND am.academy_id = asaas_subscriptions.academy_id
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1
    FROM public.profiles p
    JOIN public.academy_memberships am ON am.profile_id = p.id
    WHERE p.id = auth.uid()
      AND p.user_type = 'staff'
      AND am.academy_id = asaas_subscriptions.academy_id
  )
);

-- service_role bypasses RLS; needed for webhook processing + reconciliation
REVOKE ALL ON public.asaas_subscriptions FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE ON public.asaas_subscriptions TO authenticated, service_role;
